# Site Settings
title:               Ethan Tompkins
tagline:             
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               "https://ethantompkins.github.io"
author:
  name:              "Ethan Tompkins"
  email:             "ethantompkins55@yahoo.com"
  twitter:           "eptomp"
  #instagram:        
  github:            "ethantompkins"
  #facebook:          
  linkedin:          "ethantompkins"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
